#!/bin/bash

echo "Getting latest irrlicht 1.8 version number:"
latest_version=$( svn info  https://irrlicht.svn.sourceforge.net/svnroot/irrlicht/branches/releases/1.8 \
                 | awk '/Last Changed Rev:/ {print $4;}')
echo "Revision $latest_version"

current_version=$( cat current_version)
echo "Current irrlicht version: $current_version"
if [ $current_version == $latest_version ]; then
    echo "No changes, exiting."
    exit
fi
echo "Applying patch from $current_version to $latest_version:"

svn diff -r $current_version:$latest_version https://irrlicht.svn.sourceforge.net/svnroot/irrlicht/branches/releases/1.8 \
      | patch -p0

echo $latest_version>current_version
echo "Done"

